#!/usr/bin/env bash

# START: Sets correct directories based on local dev machine vs Gradescope production
if [ -f "/autograder/harness.py" ]; then
    echo "[GS] Running on Gradescope container, using Gradescope vars"
    DIR="/autograder/source"
    OUTPUT_DIR="/autograder/results"
    STUDENT_SUBMISSION_DIR="/autograder/submission"
else 
    echo "[GS] Running on local dev machine, using ./localautograder/ "
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    OUTPUT_DIR="$DIR/localautograder/results"
    STUDENT_SUBMISSION_DIR="$DIR/localautograder/submission"
fi
PYTHON_JSON_TOOL="$DIR/tools/json_generator.py"
PYTHON_MUTATIONS_PARSER="$DIR/tools/parse_mutations_csv.py"
source "$DIR"/grading.config
# END: Sets correct directories based on local dev machine vs Gradescope production

###########################################################################################
#
#   Start testing the student tests
#       - run mvn test with student submission, write compiler output to results json for student debugging
#       - if that succeeds, run pitest and parse the results to a json file using python tool
#
###########################################################################################

cd "$DIR"/staging_test
rm -rf target/

# run mvn test
echo "[GS - Test Tests] Running maven tests"
mvn -B test | tee /tmp/exec_tests.out
if [ ${PIPESTATUS[0]} -eq 0 ]
then
    echo "[GS - Test Tests] student tests succeed on student solution"
    # Optionally output successful mvn test results
    if [ "$CONFIG_OUTPUT_PASSING_SANITY_TESTS" = true ] ; then
        python3 "$PYTHON_JSON_TOOL" -p -t "Student tests pass on student solution"> "$OUTPUT_DIR"/results20.json
    fi
else
    echo "[GS - Test Tests] student tests fail on student solution. Exiting..."
    python3 "$PYTHON_JSON_TOOL" -t "Student tests fail on student solution" -i /tmp/exec_tests.out > "$OUTPUT_DIR"/results20.json
    exit 1;
fi

echo "[GS - Test Tests] ] Running student tests with mutations"
mvn -B org.pitest:pitest-maven:mutationCoverage

# Score the mutant coverage
python3 "$PYTHON_MUTATIONS_PARSER" --reportpath target/pit-reports --max_points $CONFIG_MUTATIONS_MAX_SCORE --verbose $CONFIG_MUTATIONS_VERBOSE --output "$OUTPUT_DIR"/results21.json