#!/usr/bin/env bash

###########################################################################################
#
#   Make autograder:
#       - Cleans up files (all .DS_Store, staging/target, staging/src/main/java*)
#       - Creates a top level zip of only the essential files required for the
#           autograder to actually run
#
###########################################################################################

# Root folder of autograder
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd ../ && pwd )"

cd $DIR

find . -name ".DS_Store" -exec rm -rf {} \;
rm -f "$DIR"/Autograder.zip
rm -rf "$DIR"/staging_main/src/main/java/*
rm -rf "$DIR"/staging_main/target/
rm -rf "$DIR"/staging_test/src/*
rm -rf "$DIR"/staging_test/target/
zip -r Autograder.zip . -x "localautograder/*" "*.git*"